services:
  app:
    image: ghcr.io/sustainability-zhaw/sustainability-dashboard:sha-a81162d
    restart: 'no'
    networks:
    - dgraphnet
    configs:
    - source: sdconfig
      target: /usr/share/caddy/config.json
    volumes: 
    - ../sustainability-dashboard/site:/usr/share/caddy

  dlgw: 
    image: ghcr.io/sustainability-zhaw/download-gateway:sha-bba6ca5
    # build:
    #   context: ../download-gateway/
    restart: 'no'
    networks:
    - dgraphnet
    configs:
    - source: dgconfig
      target: /etc/app/config.yaml

  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet

  mq: 
    image: rabbitmq:3.11-management
    restart: 'no'
    networks:
      - dgraphnet

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-a719f16
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      TIMEOUT: 20
      DGRAPH_SERVER: http://db:8080

  db_keywords:
    image: ghcr.io/sustainability-zhaw/keyword-webhook:sha-44ddb4e
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    configs:
      - source: kwconfig
        target: /etc/app/config.json

  #  # environment:
  #  #   DB_URI: http://db:8080/graphql

  dspacer: 
    image: ghcr.io/sustainability-zhaw/extraction-dspace:sha-e48a854
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    configs:
      - source: dcconfig
        target: /etc/app/config.json

  adresolver: 
    image: ghcr.io/sustainability-zhaw/ad-resolver:sha-b73cba8
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully
    env_file:
      - ./contrib/ad_config.env 

  extraction_projects: 
    image: ghcr.io/sustainability-zhaw/extraction-projects:sha-ea16132
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    env_file:
      - ./contrib/extraction_projects_config.env 

  indexer: 
    image: ghcr.io/sustainability-zhaw/sdg-indexer:sha-5ecb012
    restart: "no"
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully
    environment:
      BATCH_INTERVAL: 20
      DB_HOST: db:8080
      LOG_LEVEL: DEBUG
      
  # DEV ENVIRONMENT COMPONENTS
  # These tools provide access to query browsers and the reverse proxy

  caddy:
    image: caddy:2.6.2
    restart: 'no'
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - dgraphnet
    ports: 
      - target: 80
        published: 8080
 
  gql_browser: 
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     volumes: 
      - ./contrib/graphiql:/usr/share/caddy

networks:
  dgraphnet:
    attachable: true

configs:
  caddyfile:
    file: ./contrib/Caddyfile
  sdconfig:
    file: ./contrib/dashboard_config.json
  dcconfig:
    file: ./contrib/digital_collection.json
  kwconfig:
    file: ./contrib/kwconfig.json
  dgconfig:
    file: ./contrib/dlgw.yaml

