services:
  app:
    build:
      context: ../sustainability-dashboard/  
    
    restart: 'no'
    networks:
    - dgraphnet
    configs:
    - source: sdconfig
      target: /usr/share/caddy/config.json

  db:
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet

  db_init:
    build:
      context: ../dgraph-schema/  
    
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      TIMEOUT: 20
      DGRAPH_SERVER: http://db:8080

  db_keywords:
    build:
      context: ../keyword-webhook/
    
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    configs:
      - source: kwconfig
        target: /etc/app/config.json
      
  # DEV ENVIRONMENT COMPONENTS
  # These tools provide access to query browsers and the reverse proxy

  caddy:
    image: caddy:2.6.2
    restart: 'no'
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - dgraphnet
    ports: 
      - target: 80
        published: 8080
  
  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    networks:
      - dgraphnet
  
  gql_browser: 
     image: caddy:2.6.2
     restart: 'no'
     networks:
      - dgraphnet
     volumes: 
      - ./contrib/graphiql:/usr/share/caddy

networks:
  dgraphnet:

configs:
  caddyfile:
    file: ./contrib/Caddyfile-frontend
  sdconfig:
    file: ./contrib/dashboard_config.json
  kwconfig:
    file: ./contrib/kwconfig.json
